Matrix Operations

In [1]:
x = matrix(nrow=4, ncol=3,data=c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [2]:
rownames(x) = c("r1", "r2", "r3", "r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [3]:
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [4]:
x = matrix(nrow=4, ncol=2, data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [6]:
d = diag(2, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 2    0    0
[2,] 0    2    0
[3,] 0    0    2

In [ ]:
Matrix Operations : Diagonal Matrix

In [7]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

Matrix Operations : Transpose

In [8]:
x = matrix(nrow=4, ncol=2, data=1.8, byrow=T)
x

     [,1] [,2]
[1,] 1.8  1.8
[2,] 1.8  1.8
[3,] 1.8  1.8
[4,] 1.8  1.8

In [10]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [11]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

Matrix Operations : Rows and column sums

In [12]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [13]:
rowSums(x)

[1]  6  8 10 12

In [14]:
colSums(x)

[1] 10 26

Rows and column means

In [15]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [16]:
rowMeans(x)

[1] 3 4 5 6

In [17]:
colMeans(x)

[1] 2.5 6.5

Access to rows, columns or submatrices

In [18]:
x = matrix (nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [19]:
x[3,]

[1] 7 8 9

In [20]:
x[,2]

[1]  2  5  8 11 14

In [21]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [22]:
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [23]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

Addition of a matrix with a constant

In [24]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [28]:
x  + 5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

In [26]:
x = matrix(nrow=4, ncol=2,data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [27]:
x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

Multiplication of a matrix with a constant

In [29]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [30]:
5 * x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

Division of a matrox with a constant

In [33]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [34]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

Addition annd Subtraction of matrices

In [35]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [36]:
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [37]:
x + y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

In [38]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [39]:
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [40]:
x-y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

Multiplication of matrices

In [41]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [42]:
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [43]:
y

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [45]:
x %*% y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [46]:
y %*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [47]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [48]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [49]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
Concatenating matrices

In [50]:
x = matrix(nrow=3, ncol=2, data= 1:6,  byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

In [51]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

In [52]:
rbind(x,y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [53]:
cbind(x,y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

Inverse of Matrix

In [54]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

Eigen values and eigen vectors of matrix

In [58]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16