Name : Vaishnavi Khopkar
Roll No : 23102A0074
Branch : CMPN-A

R as a calculator

In [1]:
 2 ^  3

1

In [2]:
2**3

8

In [1]:
2 ^ 0.5

[1] 1.414214

In [2]:
2 ** 0.5

[1] 1.414214

In [3]:
2 ^ -0.5

[1] 0.7071068

Power operator with scalar

In [4]:
c(2,3,5,7) ^ 2

[1]  4  9 25 49

In [5]:
c(2,3,5,7) ^ c(2,3)

[1]   4  27  25 343

In [6]:
c(1,2,3,4,5,6) ^ c(2,3,4)

[1]    1    8   81   16  125 1296

In [7]:
c(2,3,5,7) ^ c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

Integer divsion with scalar

In [9]:
2 %/% 2

[1] 1

In [10]:
5 %/% 2

[1] 2

In [11]:
7 %/% 3

[1] 2

In [12]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

Integer divsion with data vector

In [13]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [14]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

Modulo Divsion (x mod y) with scalars

In [15]:
 2 %% 2

[1] 0

In [16]:
3 %% 2

[1] 1

In [17]:
7 %% 3

[1] 1

In [18]:
7 %% 4

[1] 3

In [19]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [20]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [21]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

R as a Calculator
Maximum

In [22]:
max(1.2, 3.4, -7.8)

[1] 3.4

In [25]:
max( c(1.2, 3.4, -7.8))

[1] 3.4

Minimum

In [26]:
min(1.2, 3.4, -7.8)

[1] -7.8

In [27]:
min ( c(1.2, 3.4, -7.8) )

[1] -7.8

Arithmetic mean

In [28]:
mean(2,3,4)

[1] 2

In [29]:
mean(c (2,3,4))

[1] 3

Examples

In [30]:
abs(-4)

[1] 4

In [31]:
abs (c(-2,-2,-3,-4,5))

[1] 2 2 3 4 5

In [32]:
sqrt(4)

[1] 2

In [33]:
sqrt(c (4,9,16,25))

[1] 2 3 4 5

Examples

In [35]:
sum(c(2,3,5,7))

[1] 17

In [36]:
prod(c(2,3,5,7))

[1] 210

In [37]:
round(1.23)

[1] 1

In [38]:
round(1.83)

[1] 2

In [39]:
log(10)

[1] 2.302585

In [40]:
log(exp(1))

[1] 1

In [41]:
log(c(10, 100, 1000))

[1] 2.302585 4.605170 6.907755

In [42]:
log10(10)

[1] 1

In [43]:
log(100)

[1] 4.60517

In [44]:
log10(c(10, 100, 1000))

[1] 1 2 3

Assignments

In [46]:
x1 = c(1,2,3,4)
x1

[1] 1 2 3 4

In [47]:
x2 = x1^2
x2

[1]  1  4  9 16

In [48]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

In [51]:
sum(c(1,2,3,4)) * prod(c(1,2))

[1] 20

In [52]:
abs( c(1,2,3,4) - sum (c(1,2,3,4)) * prod(c(1,2)))

[1] 19 18 17 16

In [54]:
c(1,2,3,4) - sum(c(1,2,3,4)) * prod(c(1,2))

[1] -19 -18 -17 -16

Matrix

In [56]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
Accessing any element of a matrix

In [57]:
x[3, 2]

[1] 7

Entering data row wise and column wise in a matrix

In [58]:
x= matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [60]:
y = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = TRUE)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [61]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

Properties of a Matrix

In [62]:
dim(x)

[1] 4 2

In [63]:
nrow(x)

[1] 4

In [64]:
ncol(x)

[1] 2

Properties of a Matrix

In [65]:
mode(x)

[1] "numeric"

In [66]:
attributes(x)

$dim
[1] 4 2