Missing Data

In [ ]:
x = NA
is.na(x)

[1] TRUE

In [ ]:
x = c(11, NA, 13, NA)
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

Example : How to work with missing data

In [ ]:
x = c(11,NA,13, NA)
mean(x)
mean (x, na.rm = TRUE)

[1] NA

[1] 12

Missing data : Location of missing values

In [ ]:
x = c(11,NA,13,NA)
x
which(is.na(x))

[1] 11 NA 13 NA

[1] 2 4

In [ ]:
x = c(11,NA,13,NA)
sum(is.na(x))

[1] 2

Missing data : Finding complete cases

In [ ]:
x = c(11,NA,13,NA)
x
complete.cases(x)

[1] 11 NA 13 NA

[1]  TRUE FALSE  TRUE FALSE

Missing data : finding complete data set

In [ ]:
x = c(11,NA,13,NA)
y = na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

Missing Data : Handling values

In [ ]:
x = c(11,NA,13,NA)
xy = na.omit(x)
y
mean(x)
mean(y)

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] NA

[1] 12

Conditional execution : if()

In [ ]:
x = 5
if (x > 4) x * 3
x = 3
if (x > 4) x * 3

[1] 15

In [ ]:
x = 5
x
if (x > 4) {x * 3}
x = 3
if (x > 4) {x * 3}

[1] 5

[1] 15

In [ ]:
x  = 6
if(x > 3) {
  print("The value is more than 3")
}
x = 2
if(x > 3) {
  print("The value is more than 3")
}

[1] "The value is more than 3"

Conditional execution:if else()

In [ ]:
x = 5
if (x ==3) {x = x -1} else {x = 2*x}

x

[1] 10

In [ ]:
x = 3
if ( x==3 ) {x = x-1} else {x = 2*x}
x

[1] 2

In [ ]:
x = 6
if(x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}
x = 2
if(x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"
[1] "The value is less than 3"

Conditional execution: Nested if else if()

In [ ]:
x = 5
if (x ==3) {
  x = x-1
} else if (x < 3) {
  x = x+5
} else {x = 2*x}
x

[1] 10

In [ ]:
x = 2
if (x ==3) {
  x = x-1
} else if (x < 3) {
  x = x+5
}else { x = 2*x }
x

[1] 7

In [ ]:
x = 3
if (x == 3) {
  x = x-1
} else if (x < 3) {
  x = x+5
} else { x = 2 *x}
x

[1] 2

In [ ]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
ifelse(x<6 , x^2, x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [ ]:
x = c(7,9,8,4)
ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

Some functions useful in conditional
execution:switch()

  Example 1:

In [ ]:
switch(2, "apple", "banana", "orange")

[1] "banana"

In [ ]:
switch(1, "apple", "banana", "orange")

[1] "apple"

Example 2:

In [ ]:
switch("colour", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] "blue"

In [ ]:
switch("volume", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] 50

Example 3:

In [ ]:
switch(4, "apple", "banana", "orange")
switch("size", "colour" = "blue", "gender" = "male", "volume" = 50)

Some functions useful in conditional
execution: which()

In [ ]:
x= c(10,15,8,14,6,12)
x

[1] 10 15  8 14  6 12

In [ ]:
which(x == 14)

[1] 4

In [ ]:
which(x != 12)

[1] 1 2 3 4 5

In [ ]:
which (x !=12)

[1] 1 2 3 4 5

In [ ]:
which (x > 10)

[1] 2 4 6

In [ ]:
x = matrix(nrow=3 ,ncol =3, data= 1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [ ]:
which.min(x)

[1] 1

In [ ]:
which.max(x)

[1] 9

In [ ]:
which(x %% 2 == 1)

[1] 1 3 5 7 9

In [ ]:
which(x %% 2 == 1, arr.ind=TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3